export interface Product {
  id: number
  name: string
  category: string
  brand: string
  price: number
  oldPrice: number | null
  rating: number
  reviews: number
  image: string
  specs: string
  badge: string | null
  isSeasonalOffer: boolean
}

export const initialProducts: Product[] = [
  {
    id: 1,
    name: "Dell XPS 15",
    category: "laptops",
    brand: "Dell",
    price: 45999,
    oldPrice: 52000,
    rating: 4.9,
    reviews: 128,
    image: "/dell-xps-15-laptop-silver-premium.jpg",
    specs: "Intel Core i7, 16GB RAM, 512GB SSD",
    badge: "الأكثر مبيعاً",
    isSeasonalOffer: true,
  },
  {
    id: 2,
    name: "HP Spectre x360",
    category: "laptops",
    brand: "HP",
    price: 42500,
    oldPrice: null,
    rating: 4.8,
    reviews: 96,
    image: "/hp-spectre-x360.png",
    specs: "Intel Core i7, 16GB RAM, 1TB SSD",
    badge: null,
    isSeasonalOffer: false,
  },
  {
    id: 3,
    name: "Lenovo ThinkPad X1 Carbon",
    category: "laptops",
    brand: "Lenovo",
    price: 48000,
    oldPrice: 55000,
    rating: 4.9,
    reviews: 203,
    image: "/lenovo-thinkpad-x1-carbon-black-business-laptop.jpg",
    specs: "Intel Core i7, 32GB RAM, 1TB SSD",
    badge: "جديد",
    isSeasonalOffer: false,
  },
  {
    id: 4,
    name: "ASUS ROG Strix G15",
    category: "laptops",
    brand: "ASUS",
    price: 38999,
    oldPrice: 42000,
    rating: 4.7,
    reviews: 156,
    image: "/asus-rog-strix-gaming-laptop-rgb.jpg",
    specs: "AMD Ryzen 9, 16GB RAM, RTX 4060",
    badge: "للألعاب",
    isSeasonalOffer: true,
  },
  {
    id: 5,
    name: "MSI Katana 15",
    category: "laptops",
    brand: "MSI",
    price: 35500,
    oldPrice: null,
    rating: 4.6,
    reviews: 89,
    image: "/msi-katana-gaming-laptop-black.jpg",
    specs: "Intel Core i7, 16GB RAM, RTX 4050",
    badge: null,
    isSeasonalOffer: false,
  },
  {
    id: 6,
    name: "Samsung Galaxy Book3 Pro",
    category: "laptops",
    brand: "Samsung",
    price: 44000,
    oldPrice: 48000,
    rating: 4.8,
    reviews: 112,
    image: "/samsung-galaxy-book3-pro-thin-laptop.jpg",
    specs: "Intel Core i7, 16GB RAM, 512GB SSD",
    badge: "شاشة AMOLED",
    isSeasonalOffer: true,
  },
  {
    id: 7,
    name: "ASUS ROG Desktop",
    category: "desktops",
    brand: "ASUS",
    price: 65000,
    oldPrice: 72000,
    rating: 4.9,
    reviews: 67,
    image: "/asus-rog-gaming-desktop-pc-rgb-tower.jpg",
    specs: "Intel Core i9, 32GB RAM, RTX 4080",
    badge: "للألعاب",
    isSeasonalOffer: true,
  },
  {
    id: 8,
    name: "MSI MEG Trident X",
    category: "desktops",
    brand: "MSI",
    price: 58000,
    oldPrice: null,
    rating: 4.8,
    reviews: 45,
    image: "/msi-meg-trident-compact-gaming-pc.jpg",
    specs: "Intel Core i7, 32GB RAM, RTX 4070",
    badge: null,
    isSeasonalOffer: false,
  },
  {
    id: 9,
    name: 'Samsung Odyssey G7 32"',
    category: "monitors",
    brand: "Samsung",
    price: 18500,
    oldPrice: 22000,
    rating: 4.9,
    reviews: 234,
    image: "/samsung-odyssey-g7-curved-gaming-monitor.jpg",
    specs: '32", QHD, 240Hz, 1ms',
    badge: "منحني",
    isSeasonalOffer: true,
  },
  {
    id: 10,
    name: "ASUS ProArt PA278CV",
    category: "monitors",
    brand: "ASUS",
    price: 12500,
    oldPrice: null,
    rating: 4.7,
    reviews: 89,
    image: "/asus-proart-professional-monitor.jpg",
    specs: '27", QHD, IPS, USB-C',
    badge: "للمصممين",
    isSeasonalOffer: false,
  },
  {
    id: 11,
    name: "Samsung Galaxy Tab S9",
    category: "tablets",
    brand: "Samsung",
    price: 28000,
    oldPrice: 32000,
    rating: 4.8,
    reviews: 156,
    image: "/samsung-galaxy-tab-s9-tablet-with-s-pen.jpg",
    specs: '11", Snapdragon 8 Gen 2, 256GB',
    badge: "الأحدث",
    isSeasonalOffer: false,
  },
  {
    id: 12,
    name: "Kingston NV2 1TB",
    category: "storage",
    brand: "Kingston",
    price: 2800,
    oldPrice: 3200,
    rating: 4.6,
    reviews: 312,
    image: "/kingston-nv2-nvme-ssd-drive.jpg",
    specs: "NVMe M.2, 3500MB/s قراءة",
    badge: null,
    isSeasonalOffer: false,
  },
  {
    id: 13,
    name: "SanDisk Extreme Pro 2TB",
    category: "storage",
    brand: "SanDisk",
    price: 5500,
    oldPrice: null,
    rating: 4.8,
    reviews: 178,
    image: "/sandisk-extreme-pro-portable-ssd-orange.jpg",
    specs: "SSD خارجي, 2000MB/s",
    badge: null,
    isSeasonalOffer: false,
  },
  {
    id: 14,
    name: "WD Black SN850X 2TB",
    category: "storage",
    brand: "Western Digital",
    price: 7200,
    oldPrice: 8500,
    rating: 4.9,
    reviews: 245,
    image: "/wd-black-sn850x-nvme-gaming-ssd.jpg",
    specs: "NVMe M.2, 7300MB/s قراءة",
    badge: "للألعاب",
    isSeasonalOffer: true,
  },
  {
    id: 15,
    name: "Samsung 990 Pro 2TB",
    category: "storage",
    brand: "Samsung",
    price: 8500,
    oldPrice: 9500,
    rating: 4.9,
    reviews: 189,
    image: "/samsung-990-pro-nvme-ssd-black.jpg",
    specs: "NVMe M.2, 7450MB/s قراءة",
    badge: "الأسرع",
    isSeasonalOffer: false,
  },
  {
    id: 16,
    name: "ASUS ROG Delta S",
    category: "accessories",
    brand: "ASUS",
    price: 4500,
    oldPrice: null,
    rating: 4.7,
    reviews: 134,
    image: "/asus-rog-delta-s-gaming-headset-rgb.jpg",
    specs: "سماعات للألعاب, USB-C",
    badge: null,
    isSeasonalOffer: false,
  },
  {
    id: 17,
    name: "MSI Gaming Keyboard",
    category: "accessories",
    brand: "MSI",
    price: 2200,
    oldPrice: 2800,
    rating: 4.6,
    reviews: 89,
    image: "/msi-mechanical-gaming-keyboard-rgb.jpg",
    specs: "ميكانيكية, RGB, Cherry MX",
    badge: null,
    isSeasonalOffer: false,
  },
  {
    id: 18,
    name: "Samsung T7 Shield 2TB",
    category: "storage",
    brand: "Samsung",
    price: 4800,
    oldPrice: 5500,
    rating: 4.8,
    reviews: 267,
    image: "/placeholder.svg?height=400&width=400",
    specs: "SSD خارجي مقاوم للصدمات",
    badge: "مقاوم للماء",
    isSeasonalOffer: false,
  },
]

export const categories = [
  { id: "all", label: "الكل", icon: null },
  { id: "laptops", label: "لاب توب", icon: "Laptop" },
  { id: "desktops", label: "كمبيوتر مكتبي", icon: "Cpu" },
  { id: "monitors", label: "شاشات", icon: "Monitor" },
  { id: "tablets", label: "تابلت", icon: "Tablet" },
  { id: "storage", label: "تخزين", icon: "HardDrive" },
  { id: "accessories", label: "إكسسوارات", icon: "Headphones" },
]
